# Generated by Django 5.0.7 on 2024-07-20 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locators', '0002_remove_customuser_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latlong',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
