# Generated by Django 5.0.7 on 2024-07-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locators', '0004_alter_customuser_managers_alter_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latlong',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='latlong',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
